const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..');
const assets=['./index.html','./manifest.json','./logo.png','./icon-192x192.png','./icon-512x512.png'];
function walk(dir){for(const entry of fs.readdirSync(dir,{withFileTypes:true})){const file=path.join(dir,entry.name);if(entry.isDirectory())walk(file);else if(!file.endsWith('input.css')&&!file.endsWith('tailwind.js'))assets.push('./'+path.relative(root,file).replaceAll('\\','/'));}}
for(const dir of ['src','styles','vendor'])walk(path.join(root,dir));
const hash=crypto.createHash('sha256');for(const file of assets.sort())hash.update(file).update(fs.readFileSync(path.join(root,file)));
const cache='inventario-parejas-shell-'+hash.digest('hex').slice(0,16);
fs.writeFileSync(path.join(root,'sw.js'),`// Generated by npm run build:cache. Public assets only; no auth/API caching.
const CACHE = ${JSON.stringify(cache)};
const ASSETS = ${JSON.stringify(['./',...assets],null,2)};
const URLS = new Set(ASSETS.map(p => new URL(p, self.registration.scope).href));
self.addEventListener('message', event => { if(event.data?.type === 'ACTIVATE_UPDATE') self.skipWaiting(); });
self.addEventListener('install', event => {
  event.waitUntil(caches.open(CACHE).then(cache => cache.addAll(ASSETS)));
  // Wait for old tabs to close; do not replace code during an inventory capture.
});
self.addEventListener('activate', event => {
  event.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(k => k.startsWith('inventario-parejas-shell-') && k !== CACHE).map(k => caches.delete(k)))).then(() => self.clients.claim()));
});
self.addEventListener('fetch', event => {
  if (event.request.method !== 'GET' || !URLS.has(event.request.url)) return;
  event.respondWith(caches.open(CACHE).then(async cache => (await cache.match(event.request)) || fetch(event.request)));
});
`);
console.log(cache);
